# Summer Analytics 2021 - Basic Data Analysis

- #### Welcome to your second assignment, on basic data analysis!
- #### This Assignment is ungraded

### 1) Import Pandas and Numpy

### 2) Import the dataset and  Assign it to a variable called Chipo

#### Import the dataset from this url 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv '
#### REMEMBER: It is a .tsv file , you will have to do some research on how to read .tsv files first!

### 3) See the first 10 entries

### 4) What is the number of observations in the dataset?

### 5) What is the number of columns in the dataset?

### 6) Print the name of all the columns.

### 7) Which was the most-ordered item?

### 8) For the most-ordered item, how many items were ordered?

### 9) What was the most ordered item in the choice_description column?

### 10) How many items were ordered in total?

### 11) Turn the item price into a float

### 12) How much was the revenue for the period in the dataset?
#### Revenue will be the sum of quantity * item_price!

### 13) How many orders were made in the period?

### 14) What is the average revenue amount per order?

### 15) How many different items are sold?